### ISSUE TITLE
could not locate an entity named 'User' in this model.'

### ISSUE THREAD

**Issue by mediashock** [RealmTeam/CoreDataHelper#10]
I now tried to implement this helper twice and both times I got this error when I try to make a new User

`'NSInternalInconsistencyException', reason: '+entityForName: could not locate an entity named 'User' in this model.'`

I initiate in application did load using 
`CDHelper.initializeWithMainContext(self.persistentContainer.viewContext) // New XCode 8/Swift 3 template
`

I have the model swift class for User
Core data works fine but not with this helper :( any ideas?

**Comment by lobodart** [comment]
It looks like the error is not coming from the helper. I invite you to have a look at [this answer](https://stackoverflow.com/questions/7100302/coredata-error-entityforname-could-not-locate-an-nsmanagedobjectmodel-for-ent?answertab=active#tab-top).

**Comment by mediashock** [comment]
I tried with a totally new project using different names and still get it :(  I checked the spelling, the coredata file is empty ...

**Comment by mediashock** [comment]
I have an empty Sounds.xcdatamodeld  and I have this code in the delegate.

>     lazy var persistentContainer: NSPersistentContainer = {
        /*
         The persistent container for the application. This implementation
         creates and returns a container, having loaded the store for the
         application to it. This property is optional since there are legitimate
         error conditions that could cause the creation of the store to fail.
         */
        let container = NSPersistentContainer(name: "Sounds")
        container.loadPersistentStores(completionHandler: { (storeDescription, error) in
            if let error = error as NSError? {
                // Replace this implementation with code to handle the error appropriately.
                // fatalError() causes the application to generate a crash log and terminate. You should not use this function in a shipping application, although it may be useful during development.
                
                /*
                 Typical reasons for an error here include:
                 * The parent directory does not exist, cannot be created, or disallows writing.
                 * The persistent store is not accessible, due to permissions or data protection when the device is locked.
                 * The device is out of space.
                 * The store could not be migrated to the current model version.
                 Check the error message to determine what the actual problem was.
                 */
                fatalError("Unresolved error \(error), \(error.userInfo)")
            }
        })
        return container
    }()
    
    // MARK: - Core Data Saving support
    
    func saveContext () {
        let context = persistentContainer.viewContext
        if context.hasChanges {
            do {
                try context.save()
            } catch {
                // Replace this implementation with code to handle the error appropriately.
                // fatalError() causes the application to generate a crash log and terminate. You should not use this function in a shipping application, although it may be useful during development.
                let nserror = error as NSError
                fatalError("Unresolved error \(nserror), \(nserror.userInfo)")
            }
        }
    }

>

**Comment by lobodart** [comment]
How CoreData can find the `User` entity if your model is empty? 😞
