### ISSUE TITLE
New versión?

### ISSUE THREAD

**Issue by resand** [RealmTeam/CoreDataHelper#11]
Not yet released version 2.0.0?

**Comment by lobodart** [comment]
Hello @resand! Unfortunately, I have absolutely no time for releasing the new version at this moment. I will come back to you when the new version will be released.

**Comment by resand** [comment]
ok, thanks!

**Comment by lobodart** [comment]
@resand A new version will be released in the following weeks ;)

**Comment by resand** [comment]
@lobodart great news! ;)
