### ISSUE TITLE
Swift 2.3 in Xcode 8

### ISSUE THREAD

**Issue by resand** [RealmTeam/CoreDataHelper#2]
I got an error when using Swift Xcode 2.3 on 8

> Type ‘Self’ does not conform to protocol ‘NSFetchRequestResult’

<img width="1006" alt="captura de pantalla 2016-09-26 a la s 2 00 36 p m" src="https://cloud.githubusercontent.com/assets/5307015/18847902/9e79eedc-83f1-11e6-97d7-944957e864fc.png">

**Comment by lobodart** [comment]
Did you try with the new version (1.1) for Swift 3 ? This code seems to be the one used for Swift 2.2.

**Comment by kdomingo** [comment]
Hello! I'm experiencing the same issue as @resand.

**Comment by lobodart** [comment]
Which version of Swift are you using ? Just a reminder : 

- Swift 3 -> take the last version of CDHelper (1.1 for now)
- Swift 2.x -> take the version 1.0.0

Hope it'll help.
