### ISSUE TITLE
Core Data relationship!

### ISSUE THREAD

**Issue by resand** [RealmTeam/CoreDataHelper#3]
how I access relations? exists?

**Comment by lobodart** [comment]
I am not sure to understand your question .. Can you give me an example of what you want to do ?

**Comment by resand** [comment]
Access the relationships between entities... I don't see in documentation

**Comment by lobodart** [comment]
The main purpose of the library is to create, delete and retrieve entities from CoreData. If you want to access to any entity's relationship, just retrieve it by using CoreDataHelper and then access to any property like a classic object. Tell me if you need an example.

**Comment by resand** [comment]
yes, I help much an example! thanks!
