### ISSUE TITLE
[Crash] Excv_bad_access _saveContext()

### ISSUE THREAD

**Issue by telenc** [RealmTeam/CoreDataHelper#4]
![crash](https://cloud.githubusercontent.com/assets/5463621/19185621/af0c28ac-8c82-11e6-8f94-c44da98ae7fe.png)

<img width="770" alt="capture d ecran 2016-10-07 a 11 37 11" src="https://cloud.githubusercontent.com/assets/5463621/19185548/6713d8e2-8c82-11e6-9da8-47cfc0ef4b05.png">

**Comment by lobodart** [comment]
CoreData changes must be done in the main thread ;)
