### ISSUE TITLE
How to get a single record, in this case the first?

### ISSUE THREAD

**Issue by resand** [RealmTeam/CoreDataHelper#8]
For the moment I do this` Entity.findAll().First`
is this correct?
Or there is a way to add a method something like this `Entity.first()`

**Comment by lobodart** [comment]
Your question doesn't really make sense. Which record is considered as "the first"? First `id`? First `creationDate`? CoreData doesn't know the answer. If you want to get the first record of an id list (for example), I suggest you do something like: 

```swift
let users: [User] = User.find("id != null", usingSortDescriptors: [NSSortDescriptor(key: "id", ascending: true)], limit: 1).first
```
Getting all the records and taking the first may be a long and painful task for CoreData if you have a lot of records so I discourage you from doing that.

I am currently working on a new version to make everything easier. If you want to have a look at what it looks like, read the `README.md` of the `dev` branch.

**Comment by resand** [comment]
@lobodart thanks!
